resources:
  containers:
  - container: buildbase
    image: 'iwillspeak/ullage-linux-build-base'
    options: '-m 4G'

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
    - script: 'brew install llvm'
      displayName: Brew install LLVM
    - script: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh && sh rustup.sh -y"
      displayName: Rustup
    - script: "cargo install just"
      displayName: Just
    - script: |
        export PATH=/usr/local/bin:$PATH             # Local bin (brew)
        source ~/.cargo/env
        export LLVM_SYS_80_PREFIX=/usr/local/opt/llvm
        ./build.sh test
      displayName: './build.sh test'
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  container: buildbase
  steps:
    - script: |
        python3 --version
        export PATH=${PATH}:~/.local/bin/
      displayName: Python
    - script: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh && sh rustup.sh -y"
      displayName: Rustup
    - script: "cargo install just"
      displayName: Just
    - script: |
        source ~/.cargo/env
        export PATH=${PATH}:~/.local/bin/
        export LLVM_SYS_80_PREFIX=/usr/lib/llvm-8
        ./build.sh test
      displayName: './build.sh test'
